### ISSUE TITLE
Setup linting

### ISSUE THREAD

**Issue by tmakerman** [satsigner/satsigner#10]
Create a lint file using Prettier and/or ESlint to have an opinionated take on the repo to ensure consistency and such.

From Gary's comment
https://github.com/satsigner/satsigner/pull/7#discussion_r1054255494

Currently repo has .prettierrc.js and .eslintrc.js.  Possibly we'd want to do some configuration or maybe they are fine as is.  Probably just need to decide which tool(s) to use.

**Comment by garyray-k** [comment]
Probably fine to leave the two prettier and eslint files as is, but we could add pre-commit hooks for them. 
https://prettier.io/docs/en/precommit.html

**Comment by xsats** [comment]
Just installed husk on a test branch here https://github.com/satsigner/satsigner/commit/42fc2fa75c06b001c02918e7aadf5d73ba96b82d 

Not totally sure it's setup properly as I don't seen anything different. Haven't used husky before.

**Comment by garyray-k** [comment]
Did you set up the hooks for it? The best way to test is to create a prettier formatting hook, then save a file unformatted, and commit, the file should be auto-formatted. I'll have more cycles to look into this once Christmas visitors depart.

**Comment by Psycarlo** [comment]
This is being done on the migration branch.
