### ISSUE TITLE
Standardize and document Component export style

### ISSUE THREAD

**Issue by garyray-k** [satsigner/satsigner#13]
Another comment for code standardization to be documented/adhered to.
Using `export default (props) =>` as opposed to `const ComponentName = (props) => ... export default ComponentName`

_Originally posted by @garyray-k in https://github.com/satsigner/satsigner/pull/7#discussion_r1054385766_

**Comment by tmakerman** [comment]
I'd suggest we use 
`export default class Foobar`

and named functions
`export default function Baz`

I intentionally didn't write argument list or generic types since I don't have opinion on that yet :)

https://stackoverflow.com/a/60106119
https://github.com/airbnb/javascript/tree/master/react#declaration

**Comment by tmakerman** [comment]
Also, suggest we pick a popular style guide as basis for project conventions and add addendum as necessary.  Looks like these ones are popular

https://github.com/piotrwitek/react-redux-typescript-guide
https://github.com/airbnb/javascript/tree/master/react

**Comment by garyray-k** [comment]
> Also, suggest we pick a popular style guide as basis for project conventions and add addendum as necessary. Looks like these ones are popular
> 
> https://github.com/piotrwitek/react-redux-typescript-guide https://github.com/airbnb/javascript/tree/master/react

Good idea! I'm ambivalent about the actual style but very opinionated that we should have one for consistency. 😄

**Comment by Psycarlo** [comment]
This is being done on the migration branch.
