### ISSUE TITLE
Input history explorer UI

### ISSUE THREAD

**Issue by pedromvpg** [satsigner/satsigner#2]
<img width="811" alt="image" src="https://user-images.githubusercontent.com/807505/202196726-22fbdecc-8bb4-4deb-a9f6-a136c068564f.png">

**Comment by pedromvpg** [comment]
![Image](https://user-images.githubusercontent.com/807505/202196643-df2f88a0-131f-42f6-a299-e96049c6b263.png)

**Comment by Psycarlo** [comment]
@umarluqman working on this

**Comment by Psycarlo** [comment]
https://github.com/satsigner/satsigner/pull/59
https://github.com/satsigner/satsigner/pull/67
