### ISSUE TITLE
Convert class components to function components

### ISSUE THREAD

**Issue by tmakerman** [satsigner/satsigner#20]
Latest React advice is to use function components as opposed to class components

https://react.dev/reference/react/Component

Some of the things that were previously possible through class components are now supported through React hooks.

https://stackoverflow.com/questions/36097965/when-to-use-es6-class-based-react-components-vs-functional-es6-react-components

**Comment by Parthhdoshi** [comment]
i would like to work on it can you assign to me?

**Comment by tmakerman** [comment]
Sorry for the delay! I will assign it to you.

**Comment by Fahad-Mahmood** [comment]
Can I work on this?

**Comment by tmakerman** [comment]
Hello @Parthhdoshi there is another contributor interested in working on this item.  I just wanted to check if you made any progress with this before they start working on this?

**Comment by tmakerman** [comment]
couple other useful pages I've seen
https://react.dev/reference/react/PureComponent#alternatives
https://react.dev/reference/react/Component#alternatives

**Comment by Parthhdoshi** [comment]
Yes, i can work on other item.

**Comment by tmakerman** [comment]
Ok thank you @Parthhdoshi

**Comment by Psycarlo** [comment]
This is being done on the migration branch.
