### ISSUE TITLE
Accounts UI

### ISSUE THREAD

**Issue by garyray-k** [satsigner/satsigner#6]
![Accounts](https://user-images.githubusercontent.com/39040273/208243673-fbe5a3ab-e5f3-40d6-8cb9-2401036630e9.png)
![Accounts-6](https://user-images.githubusercontent.com/39040273/208243675-57c05584-6c71-4ca5-aa72-f91922abdc93.png)
![Accounts-5](https://user-images.githubusercontent.com/39040273/208243677-ec81bf3e-cec4-4954-9d79-ba00072419ca.png)
![Accounts-4](https://user-images.githubusercontent.com/39040273/208243678-178c932d-273d-4725-acc4-89689d827ed8.png)
![Accounts-3](https://user-images.githubusercontent.com/39040273/208243679-f5583155-9bfb-4c6b-9641-7bc37f6586ff.png)
![Accounts-2](https://user-images.githubusercontent.com/39040273/208243681-8ee3fe95-5e66-4c18-a432-a7da52171018.png)
![Accounts-1](https://user-images.githubusercontent.com/39040273/208243684-f3577b78-a225-4cd6-8f38-bd78133073f6.png)

**Comment by tmakerman** [comment]
Thanks @garyray-k!

I'm starting that Mnemonic BIP39 screen. If anyone wants to join in on these we can split this out more.

**Comment by Psycarlo** [comment]
Done.
